$schema: http://json-schema.org/draft-07/schema
$id: /patterns/button-group
additionalProperties: false
required:
  - buttons
properties:
  buttons:
    type: array
    items:
      $ref: /elements/button
