$schema: http://json-schema.org/draft-07/schema
$id: /elements/button
additionalProperties: false
required:
  - label
properties:
  label:
    type: string
  icon:
    type: object
    description: Adds an icon to the button.
    properties:
      name:
        type: string
      position:
        type: string
        description: Positions the icon either in front of or after the text.
        enum:
          - start
          - end
